server:
  port: 10000
  https: false
  cert_file: ""
  key_file: ""

database:
  edge_path: "./edge-setting.db"

data:
  metrics_retain_days: 7

log:
  level: info

vsoa:
  ms_address: "vsoa://localhost:3000"
